apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api-sa
  namespace: fds-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fds-engine-sa
  namespace: fds-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter-sa
  namespace: monitoring-node
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-sa
  namespace: monitoring-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-runner-sa
  namespace: ci-cd
