upstream transaction_api {
    server 10.1.93.50:30080;
    # 실제 3-worker 클러스터 확보 시 아래처럼 확장:
    # server 10.1.93.105:30080;
    # server 10.1.93.107:30080;
    # server 10.1.93.108:30080;
}

server {
    listen 80 default_server;
    server_name edge01.fds.internal 10.1.93.50;

    location / {
        proxy_pass http://transaction_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
